modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "tab"
version = "${version}"
displayName = "Trade and Borders"
authors = "TechTastic"
description = '''
A Towny-esque Mod developed for my personal servers!
'''
logoFile = "assets/tab/icon.png"

[[dependencies.tab]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tab]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.91,)"
ordering = "AFTER"
side = "BOTH"